# Generated by Django 5.0.7 on 2024-08-13 12:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('source_identifier', models.CharField(max_length=100)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('vuln_status', models.CharField(max_length=50)),
                ('evaluator_comment', models.TextField(blank=True, null=True)),
                ('evaluator_impact', models.TextField(blank=True, null=True)),
                ('evaluator_solution', models.TextField(blank=True, null=True)),
                ('cisa_exploit_add', models.DateField(blank=True, null=True)),
                ('cisa_action_due', models.DateField(blank=True, null=True)),
                ('cisa_required_action', models.TextField(blank=True, null=True)),
                ('cisa_vulnerability_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CVESyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sync', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_criteria_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criteria', models.CharField(max_length=255)),
                ('last_modified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('cpe_last_modified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('status', models.CharField(max_length=50)),
                ('version_start_including', models.CharField(blank=True, max_length=50, null=True)),
                ('version_end_including', models.CharField(blank=True, max_length=50, null=True)),
                ('version_start_excluding', models.CharField(blank=True, max_length=50, null=True)),
                ('version_end_excluding', models.CharField(blank=True, max_length=50, null=True)),
                ('matches', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='MatchStringSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sync', models.DateTimeField()),
                ('status', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CVEConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=10)),
                ('negate', models.BooleanField()),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='serverapp.cve')),
            ],
        ),
        migrations.CreateModel(
            name='CPEMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vulnerable', models.BooleanField()),
                ('criteria', models.CharField(max_length=200)),
                ('match_criteria_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('version_start_including', models.CharField(blank=True, max_length=50, null=True)),
                ('version_end_including', models.CharField(blank=True, max_length=50, null=True)),
                ('version_start_excluding', models.CharField(blank=True, max_length=50, null=True)),
                ('version_end_excluding', models.CharField(blank=True, max_length=50, null=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpe_matches', to='serverapp.cveconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='CVENode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=10)),
                ('negate', models.BooleanField()),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='serverapp.cveconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='CPEMatchInNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vulnerable', models.BooleanField()),
                ('criteria', models.CharField(max_length=200)),
                ('match_criteria_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('version_start_including', models.CharField(blank=True, max_length=50, null=True)),
                ('version_end_including', models.CharField(blank=True, max_length=50, null=True)),
                ('version_start_excluding', models.CharField(blank=True, max_length=50, null=True)),
                ('version_end_excluding', models.CharField(blank=True, max_length=50, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpe_matches', to='serverapp.cvenode')),
            ],
        ),
        migrations.CreateModel(
            name='CVEReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('source', models.CharField(max_length=100)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='serverapp.cve')),
            ],
        ),
        migrations.CreateModel(
            name='CVEWeakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weaknesses', to='serverapp.cve')),
            ],
        ),
        migrations.CreateModel(
            name='CVSSMetricV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('version', models.CharField(blank=True, max_length=10, null=True)),
                ('vector_string', models.TextField(blank=True, null=True)),
                ('access_vector', models.CharField(blank=True, max_length=50, null=True)),
                ('access_complexity', models.CharField(blank=True, max_length=50, null=True)),
                ('authentication', models.CharField(blank=True, max_length=50, null=True)),
                ('confidentiality_impact', models.CharField(blank=True, max_length=50, null=True)),
                ('integrity_impact', models.CharField(blank=True, max_length=50, null=True)),
                ('availability_impact', models.CharField(blank=True, max_length=50, null=True)),
                ('base_score', models.FloatField(blank=True, null=True)),
                ('base_severity', models.CharField(blank=True, max_length=50, null=True)),
                ('exploitability_score', models.FloatField(blank=True, null=True)),
                ('impact_score', models.FloatField(blank=True, null=True)),
                ('ac_insuf_info', models.BooleanField(default=False)),
                ('obtain_all_privilege', models.BooleanField(default=False)),
                ('obtain_user_privilege', models.BooleanField(default=False)),
                ('obtain_other_privilege', models.BooleanField(default=False)),
                ('user_interaction_required', models.BooleanField(default=False)),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverapp.cve')),
            ],
        ),
        migrations.CreateModel(
            name='CVEDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('value', models.TextField()),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='serverapp.cve')),
            ],
            options={
                'unique_together': {('cve', 'lang')},
            },
        ),
        migrations.CreateModel(
            name='CVETag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=50)),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cve_tags', to='serverapp.cve')),
            ],
            options={
                'unique_together': {('cve', 'source', 'tag')},
            },
        ),
    ]
